---
- hosts: 172.31.17.137
  become: yes
  tasks: 
   - name: i want to install linux command
     command: hostname -f
     register: myResult
  
   - name: i want to display my first task
     debug: 
        msg: "{{myResult}}"