---
- hosts: 172.31.27.30
  become: yes
  tasks: 
   - name: install linux command
     command: hostname -f
     register: myResult
  
   - name: display my first task
     debug: 
        msg: "{{myResult}}"
    
   - name: install git
     apt: 
      name: apache2
      state: present
     when: myResult.stderr ==""

   - name: install tree
     apt: 
       name: tree
       state: present
     when: myResult.stderr !=""