---
- hosts: 172.31.27.30
  become: yes
  tasks: 
   - include_tasks: mytestfile2.yml
   - name: install webserver 
     apt: 
      name: apache2
      state: present
  
   - name: i want to copy file on ansible nodes
     template: 
       src: myindex.j2
       dest: /var/www/html/index.yml

     