---
- hosts: 172.31.31.72 
  become: yes
  tasks: 
  - include_tasks: mytestfile2.yml
  - name: install webserver on ansible nodes
    apt: 
      name: apache2
      state: present
    notify: restart webserver

  - name: copy my file into ansible nodes
    template: 
         src: myindex.j2
         dest: /var/www/html/index.html
    notify: restart webserver

  handlers:
   - name: restart webserver
     service: 
       name: apache2
       state: restarted
     notify: restart webserver