---
- hosts: 172.31.30.244
  become: yes
  tasks: 
  - include_tasks: mytestfile2.yml
    name: i want to install ansible nodes
    apt: 
      name: apache2
      state: present

  - name: i want to copy my file in ansible nodes
    template: 
        src: myindex.j2
        dest: /var/www/html/index.html
      
     
