---
- hosts: myfirstplaybook
  become: yes
  tasks: 
   - name: install webserver on ubuntu nodes
     apt:
      name: "{{mywebpackforubuntu}}"
      state: present
     when: ansible_os_family =="Debian"

   - name: start webserver on ubuntu nodes
     service: 
      name: "{{mywebpackforubuntu}}"
      state: started
     when: ansible_os_family =="Debian"

   - name: install webserver on RedHat nodes
     yum: 
      name: "{{mywebpackforredhat}}"
      state: present
     when: ansible_os_family =="RedHat"

   - name: start webserver on RedHat nodes
     service: 
       name: "{{mywebpackforredhat}}"
       state: started
     when: ansible_os_family =="RedHat"