---
- hosts: 172.31.17.137
  become: yes
  tasks: 
  - include_tasks: mytestfile2.yml
  - name: i want to install webserver on ubuntu nodes
    apt: 
     name: apache2
     state: present
  
  - name: i want to copy my file in ansible nodes
    template: 
        src: myj2
        dest: /var/www/html/index.html


  