---
- hosts: 172.31.23.40
  become: yes
  tasks: 
  - include_tasks: mytestfile2.yml
  - name: install webserver on ansible nodes
    apt: 
     name: apache2
     state: present
    notify: restartedwebserver

  - name: copy my file in ansible nodes
    template: 
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restartedwebserver

  handlers:
    - name: restartedwebserver
      service: 
         name: apache2
         state: present
      notify: restartedwebserver