---
- hosts: 172.31.29.63
  become: yes
  tasks: 
   - include_tasks: mytestfile.yml
   - name: install webserver on ubuntu nodes
     apt:
      name: apache2
      state: present
   
   - name: i want to copy file into ansible nodes
     template: 
        src: myjinja2
        dest: /var/www/html/index.html
        