---
- hosts: 172.31.17.137
  become: yes
  tasks: 
  - include_tasks: mytestfile2.yml
  - name: i want to install webserver on ansible nodes
    apt: 
     name: apache2
     state: present
    notify: restart webserver
  
  - name: i want to copy my file in ansible nodes
    template: 
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restart webserver
  
  handlers:
  - name: restart webserver
    service: 
       name: apache2
       state: restarted
    

  