---
- hosts: myplaybook
  become: yes
  tasks: 
   - name: install java on ansible nodes
     apt: 
      name: "{{mypacketforubuntu}}"
      state: present
     when: ansible_os_family =="Debian"

   - name: install webserver on RedHat nodes
     yum: 
      name: "{{mypacketforredhat}}"
      state: present
     when: ansible_os_family =="RedHat" 
