---
- hosts: myplaybook
  become: yes
  tasks: 
  - name: install java on ansible nodes
    apt: 
     name: "{{myjavapackforubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java on redhat nodes
    yum: 
     name: "{{myjavapackforredhat}}"
     state: present
     when: ansible_os_family =="RedHat"
    