---
- hosts: all
  tasks:
   - name: install webserver on anisble nodes
     apt:
      name: apache2
      state: peresent
     when: ansible_os_family =="Debian"

   - name: start webserver on ansible nodes
     service:
        name: apache2
        state: started
     when: ansible_os_family =="Debian"
