---
- hosts: all
  tasks:
   - name: install webserver on anisble nodes
     apt:
      name: apache2
      state: present
     when: ansible_os_family =="Debian"

   - name: start webserver on ansible nodes
     service:
        name: apache2
        state: started
     when: ansible_os_family =="Debian"

   - name: install webserver on ansible redhat server
     service: 
        name: httpd
        state: present
     when: ansible_os_family =="Redhat"

   - name: start webserver on ansible redhat server
     yum:
       name: httpd
       state: started
     when: ansible_os_family =="Redhat" 
