---
- hosts: all
  become: yes
  tasks: 
   - name: install webserver on ubuntu nodes
     apt: 
      name: "{{mypacketsforubuntu}}"
      state: present
     when: ansible_os_family =="Debian"

   - name: start webserver on ubuntu nodes
     service: 
      name: "{{mypacketsforubuntu}}"
      state: started
     when: ansible_os_family =="Debian"
  
   - name: install webserver on RedHat nodes
     yum: 
      name: "{{mypacketforredhat}}"
      state: present
     when: ansible_os_family =="RedHat"

   - name: start webserver on RedHat nodes
     service: 
      name: "{{mypacketforredhat}}"
      state: started
     when: ansible_os_family =="RedHat"
