---
- hosts: 172.31.27.30
  become: yes
  tasks: 
   - name: install git
     apt: 
       name: git
       state: present
     tags: mygit  
   - name: install wget
     apt: 
       name: wget
       stateeee: present
     tags: mywget
   - name: install tree
     apt: 
       name: tree
       state: present
     tags: mytree