---
- hosts: 172.31.31.72
  become: yes
  tasks: 
   - name: i want to install git
     apt: 
      name: git
      state: present
     tags: mygit
    
   - name: i want to install wget
     apt: 
       name: wget
       stateeeee: present
     tags: mywget

   - name: i want to install tree
     apt: 
       name: tree
       state: present 
     tags: mytree
      