---
- hosts: 172.31.21.173
  become: yes
  vars: 
    myvar1: git
    myvar2: wget
    myvar3: tree
  tasks: 
   - name: i want to display myvar1
     debug: 
        msg: "{{myvar1}}"
  
   - name: i want to install git
     apt: 
      name: "{{item}}"
      state: present
     loop:
       - "{{myvar1}}"
       - "{{myvar2}}"
       - "{{myvar3}}"    
