---
- hosts: all
  tasks: 
   - name: install webserver on ubuntu nodes
     apt:
      name: apache2
      state: present

   - name: install webserver on ubuntu nodes
     service: 
          name: apache2
          state: started