---
- hosts: 
  become: yes
  tasks: 
   - name: i want to install git
     apt: 
      name: git
      state: present

   - name: i want to install wget
     apt: 
      name: wget
      state: present
    
   - name: i want to iinstall tree
     apt: 
      name: tree
      state: present
      
