---
# tasks file for mytomcatrole
- include_tasks: installjava.yml
- include_tasks: tomcatuser.tml
- include_tasks: installtomcat.yml
- include_tasks: updatepermission.yml
- include_tasks: tomcatservice.yml
- include_tasks: starttomcat.yml