---
- name: give the tomcat group ownership
  file: 
    path: /opt/tomcat
    recurse: yes
    group: tomcat 
    state: directory

- name: give the tomcat group read access
  file:
    path: /opt/tomcat/conf
    recurse: yes
    mode: g+r  
    state: directory
    
- name: give tomcat group execute access
  file: 
    path: /opt/tomcat/conf
    mode: g+x
    state: directory
  
- name: make tomcat user owner of the webapps
  file: 
    path: /opt/tomcat/conf
    recurse: yes
    owner: tomcat
    name: "{{item}}"
    state: directory
  loop:
    - "{{work}}"
    - "{{temp}}"
    - "{{logs}}"
