---
# tasks file for mytomcatrole2
- include_tasks: installjava.yml
- include_tasks: createtomcatuser.yml
- include_tasks: installtomcat.yml
- include_tasks: updatepermission.yml
- include_tasks: systemservice.yml
- include_tasks: starttomcat.yml
