---
- name: give the tomcat group ownership
  file:
    path: /opt/tomcat
    recurse: yes
    group: tomcat
    state: directory
    
- name: give the tomcat group read access
  file: 
   path: /opt/tomcat/conf
   recurse: yes
   mode: g+r
   state: directory

- name: give the tomcat group execute access
  file: 
   path: /opt/tomcat/conf
   mode: g+x
   state: directory

- name: make the tomcat user the owner of the webapps
  file: 
   path: /opt/tomcat/webapps/
   recurse: yes
   owner: tomcat
   state: directory

- name: make the tomcat user the owner of the works
  file: 
   path: /opt/tomcat/works/
   recurse: yes
   owner: tomcat
   state: directory

- name: make the tomcat user the owner of the temps
  file: 
   path: /opt/tomcat/temps/
   recurse: yes
   owner: tomcat
   state: directory

- name: make the tomcat user the owner of the logs
  file: 
   path: /opt/tomcat/logs
   recurse: yes
   owner: tomcat
   state: directory